- name: Install and start Apache Httpd server on Amazon Linux
  hosts: localhost
  become: true
  gather_facts: false

  tasks:
    - name: Ensure Apache is installed
      yum:
        name: httpd
        state: present


    - name: Apache Service is started snd enabled
      service:
        name: httpd
        state: started
        enabled: yes

  
  
    - name: Deploy Simple index.html page
      copy:
        dest: /mnt/c/Users/prasa/Downloads/DevOps/session-27-ansible1/playbooks
        content: 
          <!DOCTYPE html>
          <html>
          <head>
          <title>Page Title</title>
          </head>
          <body>

          <h1>Apache is running</h1>
          <p>This is a paragraph.</p>

          </body>
          </html>