---
all:
    children:
        webservers:
            hosts:
                server1:
                    ansible_host: ec2-3-108-63-75.ap-south-1.compute.amazonaws.com
                    ansible_user: ec2-user
                    ansible_ssh_private_key_file: /mnt/c/users/prasa/downloads/.ssh/pradeepkey.pem
      


